service:
    name: hello-world

provider:
  name: cloudflare
  config:
    workers:
        helloworld: 
          routes:
            - yoursite.com/hello
    accountId: <your account id>
    zoneId: <your zone id

plugins:
  - serverless-cloudflare-workers

functions:
  helloworld:
    name: helloworld
    worker: helloworld
    script: helloWorld
    # events:
    #   - http:
    #       url: yoursite.com/hello
    #       method: GET
    #       headers:
    #         foo: bar
    #         x-client-data: value
